kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ubuntu-cluster-1
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
  - containerPort: 30010
    hostPort: 30010