apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: webapp-label
spec:
  containers:
    - name: webapp
      image: richardchesterwood/k8s-fleetman-webapp-angular:release0

---
apiVersion: v1
kind: Pod
metadata:
  name: activemq-queue
  labels:
    app: queue
spec:
  containers:
    - name: fleetman-queue
      image: richardchesterwood/k8s-fleetman-queue:release1
